# vi: syntax=python:et:ts=4

Import("*")

makefile = file(File('#/Makefile.common').abspath)
target = None
sources_map = {}

for line in makefile.readlines():
    if "objects =" in line:
        target = line.split("objects")[0]
        if len(target) == 0:
            target = "game"
        else:
            target = target.rstrip("_")
        sources_map[target] = []
    elif target:
        line = line.rstrip("\\ \n")
        if line.endswith(".o"):
            sources_map[target].append(line.lstrip().replace(".o", ".cpp"))

binaries = []

for key in sources_map:
    prog = env.Program("#/" + key + build_suffix, sources_map[key])
    binaries.append(env.Alias(key, prog))

all = env.Alias("all", binaries)
env.Default(all)
